USE [master]
GO

/****** Object:  Database [ELibraryMgmtSystem]    Script Date: 7/17/2020 10:10:17 PM ******/
CREATE DATABASE [ELibraryMgmtSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ELibraryMgmtSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ELibraryMgmtSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ELibraryMgmtSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ELibraryMgmtSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ELibraryMgmtSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ELibraryMgmtSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET  MULTI_USER 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ELibraryMgmtSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ELibraryMgmtSystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ELibraryMgmtSystem] SET  READ_WRITE 
GO


