//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibraryMgmtSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELibraryMgmtSystemEntities : DbContext
    {
        public ELibraryMgmtSystemEntities()
            : base("name=ELibraryMgmtSystemEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Document_Details> Document_Details { get; set; }
        public virtual DbSet<Document_Types> Document_Types { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
