//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibraryMgmtSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document_Details()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int DocId { get; set; }
        public string DocTitle { get; set; }
        public string DocAuthors { get; set; }
        public System.DateTime DocDateOfPublished { get; set; }
        public int DocPrice { get; set; }
        public string DocDescription { get; set; }
        public int DocTypeId { get; set; }
        public int DiscId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Document_Types Document_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
