//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibraryMgmtSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Details()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string UserName { get; set; }
        public string UserAddress { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserInterest { get; set; }
        public string UserEmail { get; set; }
        public int UserId { get; set; }
        public string UserPassword { get; set; }
        public string UserCreditCardNumber { get; set; }
        public string UserCreditCardExpiryDate { get; set; }
        public int UserCreditCardCVV { get; set; }
        public int UserTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
